version: '3.1'
services: 
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
  grafana:
    build: ./grafana
    container_name: grafana
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env
  wordpress:
    build: ./wp
    container_name: wp
    depends_on:
      - db
    ports:
      - 80:80
    env_file:
      - .env